Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,47 @@ jobs:
 
       - uses: actions/checkout@v4
 
+      - name: Install SonarQube Scanner
+        run: |          
+          curl -sL  -sSLo sonar-scanner.zip  https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610.zip
+          unzip sonar-scanner.zip
+          export PATH=$PATH:$PWD/sonar-scanner-6.2.1.4610/bin
+          pwd
+          ls -l $PWD/sonar-scanner-6.2.1.4610/bin/
+          echo "$PWD/sonar-scanner-6.2.1.4610/bin"
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21' # Specify the desired Java version here
+          distribution: 'temurin' # You can also use 'temurin', 'zulu', etc.
+
+      - name: Run SonarScanner
+        id: run-sonar-scanner
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          $PWD/sonar-scanner-6.2.1.4610/bin/sonar-scanner \
+            -Dsonar.projectKey=test-evidence \
+            -Dsonar.organization=my-evidence-test-org \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.java.jdkHome=$JAVA_HOME \
+            -Dsonar.verbose=true \
+            -Dsonar.token=$SONAR_TOKEN
+          # create evidence from sonar-scan analysis
+          set +e
+          # --FailOnAnalysisFailure causes a failure on gateway-failed sonar analysis 
+          ./examples/sonar-scan-example/bin/sonar-scan-extractor-linux-amd64  --reportTaskFile=$PWD/.scannerwork/report-task.txt > predicate.json
+          EXIT_CODE=$?
+          set -e          
+          # write the exit code to the github output so that it can be used in the evidence creation step
+          echo "------predicate.json------"
+          cat predicate.json
+          echo "------sonar-scan.log------"
+          cat sonar-scan.log
+          echo "------EXIT------"
+          echo "create-sonar-evidence=$EXIT_CODE" 
+          echo "create-sonar-evidence=$EXIT_CODE" >> $GITHUB_OUTPUT 
+
       - name: Docker Authenticate
         uses: docker/login-action@v3
         with:
